apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-application
spec:
  selector:
    matchLabels:
      app: ping-pong-application
  template:
    metadata:
      labels:
        app: ping-pong-application
    spec:
      containers:
      - name: ping-pong-application
        image: ollikortelahti/devops-with-kubernetes:ping-pong-application2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: PORT
            value: "3000"
        ports:
        - containerPort: 3000
