apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-application
spec:
  selector:
    matchLabels:
      app: ping-pong-application
  template:
    metadata:
      labels:
        app: ping-pong-application
    spec:
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: shared-pvc
      containers:
      - name: ping-pong-application
        image: ollikortelahti/devops-with-kubernetes:ping-pong-application3
        volumeMounts:
          - name: shared-volume
            mountPath: /app/files/
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: PORT
            value: "3000"
        ports:
        - containerPort: 3000
