apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-backend
  template:
    metadata:
      labels:
        app: project-backend
    spec:
      volumes:
        - name: image-volume
          persistentVolumeClaim:
            claimName: image-pvc
      containers:
      - name: project-backend
        image: docker.io/ollikortelahti/devops-with-kubernetes:project-v1.0-backend-4
        volumeMounts:
        - name: image-volume
          mountPath: /app/files
        ports:
          - containerPort: 3000
        env:
          - name: PORT
            value: "3000"
          - name: FILEPATH
            value: "/app/files"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: project-backend-svc
spec:
  type: ClusterIP
  selector:
    app: project-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
