apiVersion: batch/v1
kind: CronJob
metadata:
  name: add-todo
  namespace: project
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: add-todo
            image: docker.io/ollikortelahti/devops-with-kubernetes:project-v2.10-backend-1
            command: ["node", "/app/build/job.js"]
          restartPolicy: OnFailure
