apiVersion: apps/v1
kind: Deployment
metadata:
  name: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      labels:
        app: project
    spec:
      volumes:
        - name: image-volume
          persistentVolumeClaim:
            claimName: image-pvc
      containers:
      - name: project
        image: docker.io/ollikortelahti/devops-with-kubernetes:project-v0.6-3
        volumeMounts:
        - name: image-volume
          mountPath: /app/files
        ports:
          - containerPort: 3000
        env:
          - name: PORT
            value: "3000"
          - name: FILEPATH
            value: "/app/files"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
