apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: project-ingress
  labels:
    name: project-ingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: project-svc
            port: 
              number: 2345
