apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-application
  namespace: ping-pong-log-output-application
spec:
  selector:
    matchLabels:
      app: ping-pong-application
  template:
    metadata:
      labels:
        app: ping-pong-application
    spec:
      containers:
      - name: ping-pong-application
        image: ollikortelahti/devops-with-kubernetes:ping-pong-application8
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: PORT
            value: "3000"
          - name: DB_USER
            value: pingpong-user
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-password
                key: password
                optional: false
          - name: DB_DATABASE
            value: default
          - name: DB_HOST
            value: postgres-svc
          - name: DB_PORT
            value: "5432"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ping-pong-application-svc
  namespace: ping-pong-log-output-application
spec:
  selector:
    app: ping-pong-application
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
